/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_isolated_nodes' is deprecated, use 'has_isolated_nodes' instead
  warnings.warn(out)
/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'contains_self_loops' is deprecated, use 'has_self_loops' instead
  warnings.warn(out)
[codecarbon INFO @ 10:56:14] offline tracker init
[codecarbon ERROR @ 10:56:14] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:56:14] [setup] RAM Tracking...
[codecarbon INFO @ 10:56:14] [setup] GPU Tracking...
[codecarbon INFO @ 10:56:14] No GPU found.
[codecarbon INFO @ 10:56:14] [setup] CPU Tracking...
[codecarbon INFO @ 10:56:14] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:56:15] >>> Tracker's metadata:
[codecarbon INFO @ 10:56:15]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:56:15]   Python version: 3.9.13
[codecarbon INFO @ 10:56:15]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:56:15]   CPU count: 1
[codecarbon INFO @ 10:56:15]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:56:15]   GPU count: None
[codecarbon INFO @ 10:56:15]   GPU model: None
[codecarbon WARNING @ 10:56:15] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:56:15] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:56:15] stopping.
[codecarbon INFO @ 10:56:27] Energy consumed for RAM : 0.000012 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:56:27] Energy consumed for all CPUs : 0.000532 kWh. All CPUs Power : 161.1180239516816 W
[codecarbon INFO @ 10:56:27] 0.000544 kWh of electricity used since the begining.
[codecarbon WARNING @ 10:56:27] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:56:27] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 10:56:27] stopping.
[codecarbon INFO @ 10:56:46] offline tracker init
[codecarbon ERROR @ 10:56:46] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:56:46] [setup] RAM Tracking...
[codecarbon INFO @ 10:56:46] [setup] GPU Tracking...
[codecarbon INFO @ 10:56:46] No GPU found.
[codecarbon INFO @ 10:56:46] [setup] CPU Tracking...
[codecarbon INFO @ 10:56:46] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:56:46] >>> Tracker's metadata:
[codecarbon INFO @ 10:56:46]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:56:46]   Python version: 3.9.13
[codecarbon INFO @ 10:56:46]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:56:46]   CPU count: 1
[codecarbon INFO @ 10:56:46]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:56:46]   GPU count: None
[codecarbon INFO @ 10:56:46]   GPU model: None
[codecarbon WARNING @ 10:56:46] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:56:46] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:56:46] stopping.
[codecarbon INFO @ 10:57:02] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:57:02] Energy consumed for all CPUs : 0.000694 kWh. All CPUs Power : 159.8047713015177 W
[codecarbon INFO @ 10:57:02] 0.000710 kWh of electricity used since the begining.
[codecarbon INFO @ 10:57:09] Energy consumed for RAM : 0.000023 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:57:09] Energy consumed for all CPUs : 0.001005 kWh. All CPUs Power : 161.86063125452907 W
[codecarbon INFO @ 10:57:09] 0.001028 kWh of electricity used since the begining.
[codecarbon WARNING @ 10:57:09] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:57:09] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 10:57:09] stopping.
[codecarbon INFO @ 10:58:43] offline tracker init
[codecarbon ERROR @ 10:58:43] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 10:58:43] [setup] RAM Tracking...
[codecarbon INFO @ 10:58:43] [setup] GPU Tracking...
[codecarbon INFO @ 10:58:43] No GPU found.
[codecarbon INFO @ 10:58:43] [setup] CPU Tracking...
[codecarbon INFO @ 10:58:43] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 10:58:43] >>> Tracker's metadata:
[codecarbon INFO @ 10:58:43]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 10:58:43]   Python version: 3.9.13
[codecarbon INFO @ 10:58:43]   Available RAM : 10.000 GB
[codecarbon INFO @ 10:58:43]   CPU count: 1
[codecarbon INFO @ 10:58:43]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 10:58:43]   GPU count: None
[codecarbon INFO @ 10:58:43]   GPU model: None
[codecarbon WARNING @ 10:58:43] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:58:43] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 10:58:43] stopping.
[codecarbon INFO @ 10:58:58] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:58:59] Energy consumed for all CPUs : 0.000698 kWh. All CPUs Power : 160.491404251451 W
[codecarbon INFO @ 10:58:59] 0.000713 kWh of electricity used since the begining.
[codecarbon INFO @ 10:59:10] Energy consumed for RAM : 0.000028 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 10:59:10] Energy consumed for all CPUs : 0.001224 kWh. All CPUs Power : 161.50658353332938 W
[codecarbon INFO @ 10:59:10] 0.001251 kWh of electricity used since the begining.
[codecarbon WARNING @ 10:59:10] graceful shutdown. Exceptions:
[codecarbon WARNING @ 10:59:10] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 10:59:10] stopping.
[codecarbon INFO @ 11:00:46] offline tracker init
[codecarbon ERROR @ 11:00:46] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 11:00:46] [setup] RAM Tracking...
[codecarbon INFO @ 11:00:46] [setup] GPU Tracking...
[codecarbon INFO @ 11:00:46] No GPU found.
[codecarbon INFO @ 11:00:46] [setup] CPU Tracking...
[codecarbon INFO @ 11:00:46] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 11:00:46] >>> Tracker's metadata:
[codecarbon INFO @ 11:00:46]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 11:00:46]   Python version: 3.9.13
[codecarbon INFO @ 11:00:46]   Available RAM : 10.000 GB
[codecarbon INFO @ 11:00:46]   CPU count: 1
[codecarbon INFO @ 11:00:46]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 11:00:46]   GPU count: None
[codecarbon INFO @ 11:00:46]   GPU model: None
[codecarbon WARNING @ 11:00:46] graceful shutdown. Exceptions:
[codecarbon WARNING @ 11:00:46] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 11:00:46] stopping.
[codecarbon INFO @ 11:01:01] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:01:02] Energy consumed for all CPUs : 0.000697 kWh. All CPUs Power : 160.78372559257187 W
[codecarbon INFO @ 11:01:02] 0.000713 kWh of electricity used since the begining.
[codecarbon INFO @ 11:01:16] Energy consumed for RAM : 0.000031 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:01:16] Energy consumed for all CPUs : 0.001346 kWh. All CPUs Power : 162.40792597757778 W
[codecarbon INFO @ 11:01:16] 0.001376 kWh of electricity used since the begining.
[codecarbon WARNING @ 11:01:16] graceful shutdown. Exceptions:
[codecarbon WARNING @ 11:01:16] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 11:01:16] stopping.
[codecarbon INFO @ 11:01:34] offline tracker init
[codecarbon ERROR @ 11:01:34] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 11:01:34] [setup] RAM Tracking...
[codecarbon INFO @ 11:01:34] [setup] GPU Tracking...
[codecarbon INFO @ 11:01:34] No GPU found.
[codecarbon INFO @ 11:01:34] [setup] CPU Tracking...
[codecarbon INFO @ 11:01:34] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 11:01:34] >>> Tracker's metadata:
[codecarbon INFO @ 11:01:34]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 11:01:34]   Python version: 3.9.13
[codecarbon INFO @ 11:01:34]   Available RAM : 10.000 GB
[codecarbon INFO @ 11:01:34]   CPU count: 1
[codecarbon INFO @ 11:01:34]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 11:01:34]   GPU count: None
[codecarbon INFO @ 11:01:34]   GPU model: None
[codecarbon WARNING @ 11:01:34] graceful shutdown. Exceptions:
[codecarbon WARNING @ 11:01:34] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 11:01:34] stopping.
[codecarbon INFO @ 11:01:49] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:01:50] Energy consumed for all CPUs : 0.000707 kWh. All CPUs Power : 162.28704298950248 W
[codecarbon INFO @ 11:01:50] 0.000722 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:04] Energy consumed for RAM : 0.000031 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:05] Energy consumed for all CPUs : 0.001385 kWh. All CPUs Power : 162.6909023502315 W
[codecarbon INFO @ 11:02:05] 0.001416 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:19] Energy consumed for RAM : 0.000045 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:20] Energy consumed for all CPUs : 0.002055 kWh. All CPUs Power : 161.8648400213798 W
[codecarbon INFO @ 11:02:20] 0.002101 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:34] Energy consumed for RAM : 0.000060 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:35] Energy consumed for all CPUs : 0.002736 kWh. All CPUs Power : 162.64469149725625 W
[codecarbon INFO @ 11:02:35] 0.002797 kWh of electricity used since the begining.
[codecarbon INFO @ 11:02:49] Energy consumed for RAM : 0.000075 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:02:50] Energy consumed for all CPUs : 0.003412 kWh. All CPUs Power : 162.08400597382217 W
[codecarbon INFO @ 11:02:50] 0.003487 kWh of electricity used since the begining.
[codecarbon INFO @ 11:03:04] Energy consumed for RAM : 0.000090 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:03:05] Energy consumed for all CPUs : 0.004088 kWh. All CPUs Power : 162.4013598591988 W
[codecarbon INFO @ 11:03:05] 0.004178 kWh of electricity used since the begining.
[codecarbon INFO @ 11:03:19] Energy consumed for RAM : 0.000105 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:03:20] Energy consumed for all CPUs : 0.004766 kWh. All CPUs Power : 162.7627213196884 W
[codecarbon INFO @ 11:03:20] 0.004871 kWh of electricity used since the begining.
[codecarbon INFO @ 11:03:23] Energy consumed for RAM : 0.000109 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:03:23] Energy consumed for all CPUs : 0.004921 kWh. All CPUs Power : 163.273025537244 W
[codecarbon INFO @ 11:03:23] 0.005029 kWh of electricity used since the begining.
[codecarbon WARNING @ 11:03:23] graceful shutdown. Exceptions:
[codecarbon WARNING @ 11:03:23] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 424, in stop
    emissions_data = self._prepare_emissions_data()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 444, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_emissions'
[codecarbon WARNING @ 11:03:23] stopping.
[codecarbon INFO @ 11:03:50] offline tracker init
[codecarbon ERROR @ 11:03:50] Does not support country with ISO code US Exception occurred 'US'
[codecarbon INFO @ 11:03:50] [setup] RAM Tracking...
[codecarbon INFO @ 11:03:50] [setup] GPU Tracking...
[codecarbon INFO @ 11:03:50] No GPU found.
[codecarbon INFO @ 11:03:50] [setup] CPU Tracking...
[codecarbon INFO @ 11:03:50] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 11:03:50] >>> Tracker's metadata:
[codecarbon INFO @ 11:03:50]   Platform system: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
[codecarbon INFO @ 11:03:50]   Python version: 3.9.13
[codecarbon INFO @ 11:03:50]   Available RAM : 10.000 GB
[codecarbon INFO @ 11:03:50]   CPU count: 1
[codecarbon INFO @ 11:03:50]   CPU model: Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
[codecarbon INFO @ 11:03:50]   GPU count: None
[codecarbon INFO @ 11:03:50]   GPU model: None
[codecarbon WARNING @ 11:03:50] graceful shutdown. Exceptions:
[codecarbon WARNING @ 11:03:50] <class 'Exception'>
Traceback (most recent call last):
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 684, in __init__
    super().__init__(*args, **kwargs)
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 322, in __init__
    self._geo = self._get_geo_metadata()
  File "/home/cdonnat/.conda/envs/pytorch_geom3.9/lib/python3.9/site-packages/codecarbon/emissions_tracker.py", line 689, in _get_geo_metadata
    country_name=self._country_name,
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_country_name'
[codecarbon WARNING @ 11:03:50] stopping.
[codecarbon INFO @ 11:04:05] Energy consumed for RAM : 0.000016 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:04:06] Energy consumed for all CPUs : 0.000707 kWh. All CPUs Power : 162.30883824375167 W
[codecarbon INFO @ 11:04:06] 0.000722 kWh of electricity used since the begining.
[codecarbon INFO @ 11:04:20] Energy consumed for RAM : 0.000031 kWh. RAM Power : 3.75 W
[codecarbon INFO @ 11:04:21] Energy consumed for all CPUs : 0.001385 kWh. All CPUs Power : 162.67540911325972 W
[codecarbon INFO @ 11:04:21] 0.001416 kWh of electricity used since the begining.
